# Generated by Django 5.2.17 on 2026-08-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Whiskey', 'Whiskey'), ('Vodka', 'Vodka'), ('Rum', 'Rum'), ('Tequila', 'Tequila'), ('Gin', 'Gin')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('abv', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
