# Generated by Django 5.2.17 on 2026-09-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirits', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spirit_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
