# Generated by Django 5.2.17 on 2026-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirits', '0003_review_spirit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='spirit_default_image',
            field=models.ImageField(blank=True, null=True, upload_to='spirit_details/'),
        ),
    ]
