# Generated by Django 5.2.17 on 2026-09-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirits', '0004_spirit_spirit_default_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
