# Generated by Django 5.2.17 on 2026-09-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirits', '0005_spirit_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spirit',
            name='location',
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
